config:
  services:
    - name: service1
      endpoints:
        - url: /bbb
          delay: 500
          jsonPath: url1Get
          contentType: text/html
        - url: /aaa
          delay: 500
          jsonPath: url1Get
          contentType: text/html
